package models


import com.squareup.moshi.Json

data class Context(
    @Json(name = "c")
    val c: String = "",
    @Json(name = "dcterms")
    val dcterms: String = "",
    @Json(name = "geo")
    val geo: String = "",
    @Json(name = "loc")
    val loc: String = "",
    @Json(name = "org")
    val org: String = "",
    @Json(name = "vcard")
    val vcard: String = "",
    @Json(name = "schema")
    val schema: String = "",
    @Json(name = "title")
    val title: String = "",
    @Json(name = "id")
    val id: String = "",
    @Json(name = "relation")
    val relation: String = "",
    @Json(name = "references")
    val references: String = "",
    @Json(name = "address")
    val address: String = "",
    @Json(name = "area")
    val area: String = "",
    @Json(name = "district")
    val district: String = "",
    @Json(name = "locality")
    val locality: String = "",
    @Json(name = "postal-code")
    val postalCode: String = "",
    @Json(name = "street-address")
    val streetAddress: String = "",
    @Json(name = "location")
    val location: String = "",
    @Json(name = "latitude")
    val latitude: String = "",
    @Json(name = "longitude")
    val longitude: String = "",
    @Json(name = "organization")
    val organization: String = "",
    @Json(name = "organization-desc")
    val organizationDesc: String = "",
    @Json(name = "accesibility")
    val accesibility: String = "",
    @Json(name = "services")
    val services: String = "",
    @Json(name = "schedule")
    val schedule: String = "",
    @Json(name = "organization-name")
    val organizationName: String = "",
    @Json(name = "description")
    val description: String = "",
    @Json(name = "link")
    val link: String = "",
    @Json(name = "uid")
    val uid: String = "",
    @Json(name = "dtstart")
    val dtstart: String = "",
    @Json(name = "dtend")
    val dtend: String = "",
    @Json(name = "time")
    val time: String = "",
    @Json(name = "excluded-days")
    val excludedDays: String = "",
    @Json(name = "event-location")
    val eventLocation: String = "",
    @Json(name = "free")
    val free: String = "",
    @Json(name = "price")
    val price: String = "",
    @Json(name = "recurrence")
    val recurrence: String = "",
    @Json(name = "days")
    val days: String = "",
    @Json(name = "frequency")
    val frequency: String = "",
    @Json(name = "interval")
    val interval: String = "",
    @Json(name = "audience")
    val audience: String = ""
)